#!/bin/bash
# 
# This will setup the docker container, build it if it
# doesn't exist, and then run the tests.
#
# This is suitable for development of the docker image and test
# scripts.


DOCKER_IMAGE=devops/course_tester

# Create docker base image if it doesn't exist
image=$(docker images | grep "$DOCKER_IMAGE" | wc -l)
if [ "$image" != "1" ]; then
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
	pushd "$DIR"
	docker build -t=$DOCKER_IMAGE .
	popd
fi

# Setup a docker instance to run our tests
COURSE_LOCATION=$(cd "$1"; pwd)
COURSE_DIR='/course'

docker run -v "$COURSE_LOCATION":"$COURSE_DIR" -w /course-test $DOCKER_IMAGE bash -xe 'test_course'
