#!/bin/bash
# Test the courseware using xmllint and then try importing
# into a memory based ModuleStore.
set -e

# Find out where we are
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Simple xml lint to catch easy stuff
# Disable eval mode temp to provide a more helpful message
set +e
failed=false
while IFS= read -r xml
do
   xmllint "$xml" --noout;
   rc=$?
   case $rc in
       1)
           echo "Unclassified error occurred"
           ;;
       2)
           echo "Error in DTD"
           ;;
       3)
           echo "Validation error"
           ;;
       4)
           echo "Validation error"
           ;;
       5)
           echo "Error in schema compilation"
           ;;
       6)
           echo "Error writing output"
           ;;
       7)
           echo "Error in pattern (generated when [--pattern] option is used)"
           ;;
       8)
           echo "Error in Reader registration (generated when [--chkregister] option is used)"
           ;;
       9)
           echo "Out of memory error"
           ;;
   esac
   if [ $rc -ne 0 ]; then
       echo -e "$xml: \033[0;31mBad XML\033[0m"
       failed=true
       continue
   fi
   echo -e "$xml: \033[0;32mOK\033[0m"
done <<< "$(find /course -name \*.xml)"

if $failed; then
    echo "XML Syntax errors occurred."
    echo "Please check above for 'Bad XML' and correct them."
    exit 1
fi
set -e
cd /build/edx-platform
echo $DIR
python $DIR/py_course_test /course
echo "=========================="
