#!/bin/bash
# Test the courseware using xmllint and then try importing
# into a memory based ModuleStore.
set -e

# Find out where we are
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Simple xml lint to catch easy stuff
# Disable eval mode temp to provide a more helpful message
set +e
echo -e "\033[0;34mStarting XML Syntax Check\033[0m"
failed=false
bad_files=""
while IFS= read -r xml
do
   xmllint "$xml" --noout;
   rc=$?
   case $rc in
       1)
           echo "Unclassified error occurred"
           ;;
       2)
           echo "Error in DTD"
           ;;
       3)
           echo "Validation error"
           ;;
       4)
           echo "Validation error"
           ;;
       5)
           echo "Error in schema compilation"
           ;;
       6)
           echo "Error writing output"
           ;;
       7)
           echo "Error in pattern (generated when [--pattern] option is used)"
           ;;
       8)
           echo "Error in Reader registration (generated when [--chkregister] option is used)"
           ;;
       9)
           echo "Out of memory error"
           ;;
   esac
   if [ $rc -ne 0 ]; then
       echo -e "$xml: \033[0;31mBad XML\033[0m"
       failed=true
	   bad_files="$bad_files$xml\n"
       continue
   fi
   echo -e "$xml: \033[0;32mOK\033[0m"
done <<< "$(find /course -name \*.xml)"

if $failed; then
    echo -e "\033[0;31mXML Syntax errors occurred in the following files\033[0m:"
	echo -e $bad_files
    echo "Please check above for 'Bad XML' to find the specific errors"
	echo "and correct them."
    exit 1
fi
set -e
echo -e "\033[0;32mXML Syntax Check Successful\033[0m"

echo -e "\033[0;34mStarting JSON Syntax Check\033[0m"
for json in $(find /course -name "*.json"); do
    jsonlint -v $json
done
echo -e "\033[0;32mJSON Syntax Check Successful\033[0m"

echo -e "\033[0;34mStarting Course Import\033[0m"
cd /build/edx-platform
echo $DIR
python $DIR/py_course_test /course
echo "=========================="
